# Generated by Django 6.0.3 on 2026-04-13 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apif', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='bookedticket',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
