# Generated by Django 6.0.3 on 2026-04-13 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apif', '0002_alter_user_options_alter_bookedticket_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookedticket',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
