# Generated by Django 6.0.3 on 2026-04-17 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apif', '0003_alter_bookedticket_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookedticket',
            table='booked_tickets',
        ),
    ]
